/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorio_semana6;


/**
 *
 * @author User001
 */
public class FrameAgregarProfesor extends javax.swing.JFrame {

    private FrameProfesores padre;    
    FrameProfesores frameProfesores = new FrameProfesores();
   
    
    public FrameAgregarProfesor(FrameProfesores padre) {
        initComponents();
        this.padre = padre;
         
    }
    public FrameAgregarProfesor() {       
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAgregarProfesor = new javax.swing.JLabel();
        txtNombreProf = new javax.swing.JTextField();
        bttGuardarProf = new javax.swing.JButton();
        bttCancelarProf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAgregarProfesor.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        lblAgregarProfesor.setText("Agregar Profesor");

        txtNombreProf.setText("Agregar Profesor");
        txtNombreProf.setMaximumSize(new java.awt.Dimension(279, 22));
        txtNombreProf.setMinimumSize(new java.awt.Dimension(279, 22));

        bttGuardarProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio_semana6/Img/Group 1.png"))); // NOI18N
        bttGuardarProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttGuardarProfActionPerformed(evt);
            }
        });

        bttCancelarProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio_semana6/Img/Group 3.png"))); // NOI18N
        bttCancelarProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCancelarProfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAgregarProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .addComponent(txtNombreProf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bttGuardarProf)
                        .addGap(18, 18, 18)
                        .addComponent(bttCancelarProf)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAgregarProfesor)
                .addGap(18, 18, 18)
                .addComponent(txtNombreProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttCancelarProf)
                    .addComponent(bttGuardarProf))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttGuardarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttGuardarProfActionPerformed
        String nombreprofesor = txtNombreProf.getText();

        padre.AgregarProfesor(nombreprofesor);
        this.padre.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_bttGuardarProfActionPerformed

    
    private void bttCancelarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCancelarProfActionPerformed
        this.padre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttCancelarProfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAgregarProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttCancelarProf;
    private javax.swing.JButton bttGuardarProf;
    private javax.swing.JLabel lblAgregarProfesor;
    private javax.swing.JTextField txtNombreProf;
    // End of variables declaration//GEN-END:variables
}
