/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorio_semana6;


public class FrameAgregarCurso extends javax.swing.JFrame {

    private FrameGestordeCursos padre;    
    FrameGestordeCursos frameGestordeCursos = new FrameGestordeCursos();
     public FrameAgregarCurso(FrameGestordeCursos padre) {
        initComponents();
        this.padre = padre;
    }
    public FrameAgregarCurso() {
        initComponents();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        bttGuardarCurso = new javax.swing.JButton();
        bttSalirFAC = new javax.swing.JButton();
        lblAgregarCursos = new javax.swing.JLabel();
        txtNombreCurso = new javax.swing.JTextField();
        txtCodigoCurso = new javax.swing.JTextField();
        txtCreditoCurso = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bttGuardarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio_semana6/Img/Group 1.png"))); // NOI18N
        bttGuardarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttGuardarCursoActionPerformed(evt);
            }
        });

        bttSalirFAC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio_semana6/Img/Group 3.png"))); // NOI18N
        bttSalirFAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSalirFACActionPerformed(evt);
            }
        });

        lblAgregarCursos.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        lblAgregarCursos.setText("Agregar Cursos");

        txtNombreCurso.setText("Ingresar Nombre");
        txtNombreCurso.setMaximumSize(new java.awt.Dimension(279, 22));
        txtNombreCurso.setMinimumSize(new java.awt.Dimension(279, 22));
        txtNombreCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCursoActionPerformed(evt);
            }
        });

        txtCodigoCurso.setText("Ingresar Codigo");
        txtCodigoCurso.setMaximumSize(new java.awt.Dimension(279, 22));
        txtCodigoCurso.setMinimumSize(new java.awt.Dimension(279, 22));

        txtCreditoCurso.setText("Ingresar Creditos del curso");
        txtCreditoCurso.setMaximumSize(new java.awt.Dimension(279, 22));
        txtCreditoCurso.setMinimumSize(new java.awt.Dimension(279, 22));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bttGuardarCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttSalirFAC))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblAgregarCursos))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCodigoCurso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCreditoCurso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAgregarCursos)
                .addGap(30, 30, 30)
                .addComponent(txtNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCreditoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bttGuardarCurso)
                    .addComponent(bttSalirFAC))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttGuardarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttGuardarCursoActionPerformed
        String nuevoCurso = txtNombreCurso.getText();
       String nuevoCodigo = txtCodigoCurso.getText();
       String nuevoCredito = txtCreditoCurso.getText();
       FrameGestordeCursos frameGestordeCursos = FrameGestordeCursos.getInstancia();
       frameGestordeCursos.AgregarCursoALista(nuevoCurso, nuevoCodigo, nuevoCredito);
       this.dispose();
       frameGestordeCursos.setVisible(true);
    }//GEN-LAST:event_bttGuardarCursoActionPerformed

    private void bttSalirFACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSalirFACActionPerformed

        this.padre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttSalirFACActionPerformed

    private void txtNombreCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCursoActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrameAgregarCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttGuardarCurso;
    private javax.swing.JButton bttSalirFAC;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel lblAgregarCursos;
    private javax.swing.JTextField txtCodigoCurso;
    private javax.swing.JTextField txtCreditoCurso;
    private javax.swing.JTextField txtNombreCurso;
    // End of variables declaration//GEN-END:variables
}
