/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorio_semana6;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author User001
 */
public class FrameGestordeCursos extends javax.swing.JFrame {

    /**
     * Creates new form FrameGestordeCursos
     */
     private Curso cursoSeleccionado;
     private static FrameGestordeCursos instancia;
     DefaultListModel model = new DefaultListModel();
     List<Curso> cursos = new ArrayList<>();
     public FrameGestordeCursos() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGestordeCursos = new javax.swing.JLabel();
        bttEstudiante = new javax.swing.JButton();
        bttAgregar = new javax.swing.JButton();
        bttBuscarCurso = new javax.swing.JButton();
        bttEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCursos = new javax.swing.JList<>();
        bttProfesor = new javax.swing.JButton();
        txtCurso = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblGestordeCursos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblGestordeCursos.setText("  Gestor de cursos");

        bttEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio_semana6/Img/Group 10.png"))); // NOI18N
        bttEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEstudianteActionPerformed(evt);
            }
        });

        bttAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio_semana6/Img/Group 11.png"))); // NOI18N
        bttAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAgregarActionPerformed(evt);
            }
        });

        bttBuscarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio_semana6/Img/Group 18.png"))); // NOI18N
        bttBuscarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBuscarCursoActionPerformed(evt);
            }
        });

        bttEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio_semana6/Img/Group 12.png"))); // NOI18N
        bttEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEliminarActionPerformed(evt);
            }
        });

        lstCursos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lstCursos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "d", "f", "f", "f", "g" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstCursos);

        bttProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio_semana6/Img/Group 9.png"))); // NOI18N
        bttProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttProfesorActionPerformed(evt);
            }
        });

        txtCurso.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCurso.setText("jTextField1");
        txtCurso.setToolTipText("");
        txtCurso.setMaximumSize(new java.awt.Dimension(149, 30));
        txtCurso.setMinimumSize(new java.awt.Dimension(149, 30));
        txtCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bttBuscarCurso)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttProfesor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bttAgregar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttEstudiante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bttEliminar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lblGestordeCursos)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGestordeCursos)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttBuscarCurso)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttProfesor)
                    .addComponent(bttAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttEstudiante)
                    .addComponent(bttEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttProfesorActionPerformed
        if (VerificarCursoSeleccionado()) {
        String cursoSeleccionado = lstCursos.getSelectedValue();
        FrameProfesores frameProfesores = new FrameProfesores(this, cursoSeleccionado);
        frameProfesores.setVisible(true);
    }
    }//GEN-LAST:event_bttProfesorActionPerformed

    private void bttEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEliminarActionPerformed
     int Idx = lstCursos.getSelectedIndex();    
     if (Idx != -1) { 
        model.remove(Idx);
    }
    }//GEN-LAST:event_bttEliminarActionPerformed

    private void txtCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCursoActionPerformed
        // Hola profe :)
    }//GEN-LAST:event_txtCursoActionPerformed

    private void bttAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAgregarActionPerformed
        FrameGestordeCursos frameGestordeCursos = FrameGestordeCursos.getInstancia();
        FrameAgregarCurso ventanacurso = new FrameAgregarCurso(frameGestordeCursos);
        ventanacurso.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bttAgregarActionPerformed

    private void bttBuscarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttBuscarCursoActionPerformed
        String textoCursoBusqueda = txtCurso.getText();
        for (int i = 0; i < model.size(); i++) {
        String elemento = (String) model.getElementAt(i);
        if (elemento.equalsIgnoreCase(textoCursoBusqueda)) {
            lstCursos.setSelectedIndex(i);
            break;
        }
    }
    }//GEN-LAST:event_bttBuscarCursoActionPerformed

    private void bttEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEstudianteActionPerformed
        if (VerificarCursoSeleccionado()) {
        String cursoSeleccionado = lstCursos.getSelectedValue();
        FrameEstudiantes frameEstudiantes = new FrameEstudiantes(this,cursoSeleccionado);
        frameEstudiantes.setVisible(true);}
    }//GEN-LAST:event_bttEstudianteActionPerformed

    public void AgregarCursoALista(String nuevoCurso, String nuevoCodigo, String nuevoCredito) {
    Curso curso = new Curso(nuevoCurso, nuevoCodigo, nuevoCredito);
    cursos.add(curso);
    model.addElement(nuevoCurso);
    lstCursos.setModel(model);
}
    public static FrameGestordeCursos getInstancia() {
        if (instancia == null) {
            instancia = new FrameGestordeCursos();
        }
        return instancia;
    }
    private boolean VerificarCursoSeleccionado() {
    return lstCursos.getSelectedIndex() != -1;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameGestordeCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameGestordeCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameGestordeCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameGestordeCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameGestordeCursos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAgregar;
    private javax.swing.JButton bttBuscarCurso;
    private javax.swing.JButton bttEliminar;
    private javax.swing.JButton bttEstudiante;
    private javax.swing.JButton bttProfesor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGestordeCursos;
    private javax.swing.JList<String> lstCursos;
    private javax.swing.JTextField txtCurso;
    // End of variables declaration//GEN-END:variables
}
